### ISSUE TITLE
Pas de chargement du fichier d'import

### ISSUE THREAD

**Issue by RomainDeschamps** [altairisfr/prices#1]
Dolibarr V10
Prices V2019.1 (dernière version dispo sur github)

On revient à l'écran suivant après avoir sélectionné un fichier.

![image](https://user-images.githubusercontent.com/11922840/101042923-facf3600-357d-11eb-9a6c-1737f8e154be.png)

**Comment by altatof** [comment]
bizarre... Visuals utilise ce module tous les jours en v10 !

**Comment by RomainDeschamps** [comment]
En effet...

Avec ces mêmes versions ? : Dolibarr 10.0.7 et Prices 2019.1

**Comment by RomainDeschamps** [comment]
OK. Nécessite l'activation du module natif d'imports
