### ISSUE TITLE
v12 : impossible de déplacer les lignes dans la phase de parsing

### ISSUE THREAD

**Issue by agnesrambaud** [altairisfr/prices#2]
pb de jquery. Pas d'ancres pour déplacer les lignes du fichier à importer face aux tables dolibarr. Du coup inutilisable.

**Comment by agnesrambaud** [comment]
fix

**Comment by altatof** [comment]
Fixed : https://github.com/altairisfr/prices/commit/dda1afc5125ec9cf5acb9d6c56903de22e1cf0ba
