### ISSUE TITLE
Prices étape 3 :  NoSupplierSelected malgré la présence de l'information

### ISSUE THREAD

**Issue by agnesrambaud** [altairisfr/prices#3]
Obligation de choisir un fournisseur depuis la liste déroulante.
Bug contournable si l'on a un seul fournisseur dans le fichier d'import.

Comportement attendu : si l'information du code fournisseur est présente dans le fichier (et dans le parsing), alors il est inutile de choisir le fournisseur dans la liste déroulante.
![Nouvel_import_-_2020-12-29_09 21 24](https://user-images.githubusercontent.com/418114/103270101-9bffaf80-49b7-11eb-85cf-df27b91944b4.png)
![Nouvel_import_-_2020-12-29_09 25 04](https://user-images.githubusercontent.com/418114/103270266-bfc2f580-49b7-11eb-9bc6-b6d71211e857.png)

**Comment by altatof** [comment]
attention aux espaces en début de code !
