### ISSUE TITLE
Prices - valider catalogue : après la création (réussie) de nouveaux produits, on reste sur le même écran

### ISSUE THREAD

**Issue by agnesrambaud** [altairisfr/prices#4]
Malgré la réussite de la création de produits affichée, on reste à l'étape de création des nouveaux produits.
![Valider_le_catalogue_-_2020-12-29_09 28 45](https://user-images.githubusercontent.com/418114/103270554-7b842500-49b8-11eb-85dd-85cc1fd93ba0.png)

**Comment by agnesrambaud** [comment]
Dans la base de données : catalog_prices : 
Pour un des produits "créé" à cette étape : fk_products=-3
Les infos sont par ailleurs bien importées (libellé, ref. fourn et ref interne, catalog_prices et discount_rate, resell_unit_base_price, tva achat et vente). Prix de vente pour l'instant à  0 et fk_statut = 0.

**Comment by altatof** [comment]
Fixed : https://github.com/altairisfr/prices/commit/86732977c143c925cd9c4f513af7bd5fdf80932f
