### ISSUE TITLE
Validation du catalogue : price ne présente plus la liste des produits qui ne sont plus au catalogue

### ISSUE THREAD

**Issue by agnesrambaud** [altairisfr/prices#5]
dans dolibarr pour ce fournisseur : 564 produits
import du catalogue : 551 lignes.
De base il y a au moins 13 produits dans dolibarr qui ne sont pas dans le catalogue, + les 21 nouveaux produits, ça fait 34 produits qui ne devraient pas être au catalogue).
Ici, rien n'est présenté.

**Comment by altatof** [comment]
Fixed : https://github.com/altairisfr/prices/commit/dd0ee5e47354e4e10ab0cddae5c220b2dec37495
